### ISSUE TITLE
Prompt Composer Custom Lists and Deprecated (Style, Effect) nodes don't work!

### ISSUE THREAD

**Issue by rollingcookies** [florestefano1975/comfyui-prompt-composer#8]
!!! Exception during processing !!! 'PromptComposerCustomLists' object is not callable
Traceback (most recent call last):
  File "D:\!ComfyUI\ComfyUI\execution.py", line 289, in execute
    obj = class_def()
          ^^^^^^^^^^^
TypeError: 'PromptComposerCustomLists' object is not callable

Prompt executed in 0.01 seconds
got prompt
!!! Exception during processing !!! 'PromptComposerStyler' object is not callable
Traceback (most recent call last):
  File "D:\!ComfyUI\ComfyUI\execution.py", line 289, in execute
    obj = class_def()
          ^^^^^^^^^^^
TypeError: 'PromptComposerStyler' object is not callable

Prompt executed in 0.01 seconds

**Comment by AuricMists** [comment]
I get the same with Custom Lists.
There seems to be no code that defines what the object does - in the file ComfyUI\custom_nodes\comfyui-prompt-composer\nodes\custom_lists.py - but with my knowledge of the internal workings of ComfyUI, I may be barking up the wrong tree.

**Comment by vararth** [comment]
Getting the same error message

**Comment by Tyrin451** [comment]
Hi,

Observing how the Clothing node works, it seems the way widgets are handled might have changed.

In the current version, it looks like nodes can be auto-generated based on the content of the `ComfyUI/custom_nodes/comfyui-prompt-composer/custom-lists/` folder.

To get a functional style/effect node, it seems we just need to create a new subfolder (e.g., styler) inside custom-lists and move the relevant .txt files into it.

For instance:
```
custom-lists/
 |- clothing/
 |    |- Complex.txt
 |    |- Generic.txt
 |- styler/
 |    |- effect.txt
 |    |- lens_type.txt
 |    |- painting_style.txt
 etc...
```

This approach seems simpler for managing custom styles and effects.
